<a href="https://colab.research.google.com/github/BinBinToure/Python/blob/main/%EB%B9%84%ED%8A%B8_%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%88%98%EC%A7%91_%EB%B6%84%EC%84%9D_%EC%8B%9C%EA%B0%81%ED%99%94_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://numpy.org/doc/stable/user/whatisnumpy.html

In [ ]:
ls = [[1,2,3,4],[3,4,5],[2,3],[1],1,2,'Hello']
print(ls)

[[1, 2, 3, 4], [3, 4, 5], [2, 3], [1], 1, 2, 'Hello']


In [ ]:
# numpy 모듈을 사용하기 위한 import문
import numpy as np                          # as 뒤는 닉네임

In [ ]:
ls = [1,2,3,4,5]
arr = np.array(ls)
print(arr)
print(type(arr))   # 다차원 배열을 표현하는 타입이 ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
ls1 = [1,2,3]
ls2 = [4,7,2]
ls3 = ls1 + ls2
print(ls3)        # 파이썬 리스트의 합은 concat

[1, 2, 3, 4, 7, 2]


In [ ]:
arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr3 = arr1 + arr2
print(arr3)       # numpy의 +연산은 행렬의 +연산을 수행

[5 9 5]


In [ ]:
ls = [1,2,3] 
ls2 = ls * 3
print(ls2)        # 리스트 * 수는 원소를 반복해서 나열

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
arr = np.array(ls)
arr2 = arr * 3
print(arr2)       # numpy의 ndarray * 정수는 행렬 * 정수 연산을 수행

[3 6 9]


%%time을 마킹하면 시간을 보여줍니다

In [ ]:
%%time                        
arr = np.arange(100000)         ## p134

UsageError: Can't use statement directly after '%%time'!


In [ ]:
%%time
ls = list(range(100000))

CPU times: user 3.42 ms, sys: 904 µs, total: 4.32 ms
Wall time: 4.88 ms


In [ ]:
arr = np.random.randn(2,3)  # 2X3 행렬을 생성(원소는 랜덤하게 결정)
print(arr)

[[ 1.74266236  0.39558377  0.72324708]
 [-0.96200396 -0.5087491  -2.12983247]]


In [ ]:
arr2 = arr*3
print(arr2)

[[ 5.22798709  1.18675131  2.16974123]
 [-2.88601189 -1.5262473  -6.38949741]]


In [ ]:
print(arr)

[[ 1.74266236  0.39558377  0.72324708]
 [-0.96200396 -0.5087491  -2.12983247]]


In [ ]:
print(arr.shape)         # 구조 확인
                         # 대괄호가 2개로 시작하면 2차원

(2, 3)


In [ ]:
print(arr.ndim)          # 차원 확인

2


In [ ]:
arr.dtype         # 원소 타입 확인

dtype('float64')

In [ ]:
arr = np.array([1,2,3])
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3,4.2])       # 정수와 실수로 배열 생성 -> 모든 정수는 실수로 변환된다.
print(arr)
print(arr.dtype)
print(type(arr[0]))

In [ ]:
arr = np.array([1,2,3,4.2,'a'])   # 수와 문자열로 구성 -> 모두 문자열로 변환됨
print(arr)
print(arr.dtype)
print(type(arr[0]))

['1' '2' '3' '4.2' 'a']
<U32
<class 'numpy.str_'>


다차원 배열 생성

In [ ]:
ls = [1,2,3]
arr = np.array(ls) # 리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

In [ ]:
ls = [[1,2,3],[2,5,6]]
arr = np.array(ls) # 리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

In [ ]:
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

In [ ]:
arr = np.zeros(10)
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

In [ ]:
arr = np.zeros((3,6))
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

In [ ]:
arr = np.ones((3,6))
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)     # defalut는 float이다

In [ ]:
arr = np.arange(20)
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

In [ ]:
arr = np.arange(3,20,4)
print(arr)
print("구조 : ",arr.shape)
print("차원 : ",arr.ndim)
print("원소 형식 : ",arr.dtype)

원소 타입

In [ ]:
arr = np.array([1,2,3])
print(type(arr[0]), type(arr[1]), type(arr[2]))
print(arr.dtype)

In [ ]:
arr = np.array([1,2,4.2])
print(type(arr[0]), type(arr[1]), type(arr[2]))
print(arr.dtype)

In [ ]:
arr = np.array([1,2,4.2], dtype = np.int32)         ## dtype 인자를 이용하여 명시적으로 원소 형식 결정
print(type(arr[0]), type(arr[1]), type(arr[2]))
print(arr.dtype)
print(arr)

산술 연산

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("====")
arr2 = arr * arr
print(arr2)

In [ ]:
arr2 = arr - arr            # p143
print(arr2)

In [ ]:
arr2 = 1 / arr
print(arr2)

In [ ]:
arr2 = arr ** 0.5
print(arr2)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,0,2])
filter = arr1 > arr2
print(filter)

색인 및 슬라이싱

In [ ]:
arr = np.arange(1000)
print(arr[5:8])

In [ ]:
print(arr[:8])

In [ ]:
print(arr[995:])

In [ ]:
print(arr[-5:])

In [ ]:
arr = np.zeros(30)
print(arr)

In [ ]:
arr[5:8] = 7
print(arr)

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

In [ ]:
print(arr[0])
print(arr[1])
print(arr[2])

In [ ]:
print(arr[0][2])

In [ ]:
print(arr[0,2])

In [ ]:
# 소스 배열을 가지고 간단한 실험을 하기 위해서 복사하여 사용하기
cp_arr = arr.copy()
print(cp_arr)
print("====")
cp_arr[0][1]=8      # 원본 내용이 바뀌지 않음
print(cp_arr)
print("====")
print(arr)

In [ ]:
cp_arr = arr            # arr과 cp_arr은 같은 개체를 참조
print(cp_arr)
print("====")
cp_arr[0][1]=8
print(cp_arr)           # 원본이 바뀜
print("====")
print(arr)

In [ ]:
arr = np.array([1,2,3])

filter = arr>=2
print(filter)

In [ ]:
res = arr[filter]
print(res)

**구조 변경**

In [ ]:
arr = np.arange(96)               # p155
print("구조 : ", arr.shape)
print("차원 : ", arr.ndim)

In [ ]:
arr2 = arr.reshape((6,16))              
print("구조 : ", arr2.shape)
print("차원 : ", arr2.ndim)

In [ ]:
# arr2 = arr.reshape((7,13))              
# print("구조 : ", arr2.shape)        # 구조 변경할때 요소의 개수가 같을 때만 구조 변경할 수 있음 (96이므로 6*16은 가능, 7*13은 불가능)
# print("차원 : ", arr2.ndim)

In [ ]:
arr2 = arr.reshape((6,-1))            # 구조 변경 요청할 때 하나의 차원은 -1로 표현 가능(알아서 계산)
print("구조 : ", arr2.shape)
print("차원 : ", arr2.ndim)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.T
print(arr)
print("====")
print(arr2)

In [ ]:
arr2 = arr.transpose()        # arr.T와 arr.transpose()는 같은 결과(전치행렬)를 반환한다.
print(arr)
print("====")
print(arr2)

In [ ]:
arr = np.arange(10)
print(arr)

In [ ]:
arr2 = np.sqrt(arr)
print(arr2)

In [ ]:
arr1 = np.random.randn(2,3)
print(arr1)
print("===")
arr2 = np.random.randn(2,3)
print(arr2)

In [ ]:
arr3 = np.maximum(arr1, arr2)
print(arr3)

**Numpy 안으로**

In [ ]:
# 잠시 파이썬 기본 문법 - 리스트 컴프리헨션
xs = [x*x+2*x+3 for x in range(1,10)] #리스트 컴프리헨션
print(xs) 

In [ ]:
xs = []
for x in range(1,10) : 
  xs.append(x*x+2*x+3)
print(xs)

In [ ]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [ ]:
# 파이썬 기초 문법 - zip 사용 예
ls1 = [1,2,3]
ls2 = ['가','나','다']
for e1,e2 in zip(ls1, ls2) :
  print(e1, e2)

In [ ]:
# 리스트 컴프리헨션
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]
print(result)

In [ ]:
result = np.where(cond, xarr, yarr)
print(result)

In [ ]:
result = []
for x,y,c in zip(xarr, yarr, cond) :
  if c : 
    result.append(x)
  else :
    result.append(y)
print(result)

In [ ]:
result = np.where(cond,1,2)
print(result)

In [ ]:
heights = np.random.normal(172.4,5,100)        # 평균이 172.4 표준편차 5인 표본 1000개를 생성
print(heights)

In [ ]:
print("평균 : ",heights.mean())   # print("평균 : ", np.mean(heights))
print("합계 : ",heights.sum())    # print("합계 : ", np.sum(heights))

In [ ]:
h2 = heights.reshape(20, -1)
print("구조 : ",h2.shape)
print(h2)

In [ ]:
print("평균(축0) : ", h2.mean(axis=0))      # 컬럼 별 평균
print("평균(축1) : ", h2.mean(axis=1))      # 로우 별 평균

In [ ]:
print("합계(축0) : ",h2.sum(axis=0))         # 컬럼 별 합계
print("합계(축1) : ",h2.sum(axis=1))         # 로우 별 합계

In [ ]:
print("분산 : ",h2.var())         
print("표준편차 : ",h2.std())         

In [ ]:
print("최솟값 : ",h2.min())
print("최댓값 : ",h2.max())

In [ ]:
print("최솟값이 있는 위치 : ", heights.argmin())
print("최댓값이 있는 위치 : ", heights.argmax())
print(heights[heights.argmin()], heights[heights.argmax()])

In [ ]:
arr = np.array([1,2,4,2,7])
print("누적 합계 : ", arr.cumsum())
print("누적 곱 : ", arr.cumprod())

In [ ]:
arr.sort()
print(arr)

In [ ]:
ua = np.unique(arr)
print(ua)

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,3],[1,2],[4,5]])
re = x.dot(y)
print(x)
print("===")
print(y)
print("===")
print(re)

**난수**

In [ ]:
for _ in range(10) :
  print(np.random.uniform(-2,3))      # -2와 3사이의 랜덤한 실수 반환

In [ ]:
for _ in range(20) :
  print(np.random.randint(1,5), end = ' ')  # 1에서 5사이의 랜덤한 정수 반환
print()

In [ ]:
volan = [1,7,2,8,9]
for _ in range(20) : 
  print(np.random.choice(volan), end = ' ')
print()